"""GUI-free backend for Thai-to-PUA encoding and composite PUA font generation."""

from thaipua.core.creation_engine import (
    ParsedStringTable,
    StringEntry,
    StringTableError,
    parse_strings_file,
    write_strings_file,
)
from thaipua.core.encoding import (
    PuaEncodingMap,
    detect_text_encoding,
    load_decode_table,
    load_encoding_map,
    load_pua_map_dict,
    normalize_sara_am,
)
from thaipua.core.file_codec import decode_files, encode_files
from thaipua.core.fonttools import (
    ABOVE_VOWELS,
    BELOW_VOWELS,
    THAI_CONSONANTS,
    TONE_MARKS,
    CompositeSpec,
    ConsonantSettings,
    GlyphSubstitution,
    GsubAlternateIndex,
    Metadata,
    Offset,
    PlacementSettings,
    SnapConfig,
    ThaiPuaFontGenerator,
    default_placement_settings,
    find_glyph_substitutions,
    iter_composite_specs,
    load_placement_settings,
    save_placement_settings,
    settings_to_dict,
)
from thaipua.core.profiles import ResolvedProfile, resolve_settings_profile

__all__ = [
    "ABOVE_VOWELS",
    "BELOW_VOWELS",
    "THAI_CONSONANTS",
    "TONE_MARKS",
    "CompositeSpec",
    "ConsonantSettings",
    "GlyphSubstitution",
    "GsubAlternateIndex",
    "Metadata",
    "Offset",
    "ParsedStringTable",
    "PlacementSettings",
    "PuaEncodingMap",
    "ResolvedProfile",
    "SnapConfig",
    "StringEntry",
    "StringTableError",
    "ThaiPuaFontGenerator",
    "decode_files",
    "default_placement_settings",
    "detect_text_encoding",
    "encode_files",
    "find_glyph_substitutions",
    "iter_composite_specs",
    "load_decode_table",
    "load_encoding_map",
    "load_placement_settings",
    "load_pua_map_dict",
    "normalize_sara_am",
    "parse_strings_file",
    "resolve_settings_profile",
    "save_placement_settings",
    "settings_to_dict",
    "write_strings_file",
]
